create table if not exists users(
    id bigint primary key generated by default as identity unique ,
    username varchar(250) not null ,
    email varchar(250) not null ,
    password varchar(250) not null ,
    regdate timestamp not null
);

create table if not exists roles(
    id bigint primary key generated by default as identity unique ,
    name varchar(250) not null
);

create table if not exists user_role(
    user_id bigint not null check ( user_id > 0 ) unique,
    role_id bigint not null check ( role_id > 0 ),
    primary key (user_id, role_id) ,
    foreign key (user_id) references users(id) on delete cascade on update cascade ,
    foreign key (role_id) references roles(id) on delete cascade on update cascade
);

insert into roles(name) values ('guest');
insert into roles(name) values ('user');
insert into roles(name) values ('admin');

insert into users(username, email, password, regdate)
VALUES ('admin', 'admin@admin.ru', 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=', now());

insert into user_role(user_id, role_id)VALUES (1, 3);